name: Build project and run Lighthouse CI
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: npm install
        run: |
          npm install

      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: "inspiring-wozniak-54afa7"

      - name: Wait for Netlify build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Redirect rules - inspiring-wozniak-54afa7
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Lighthouse CI
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
          npm install -g @lhci/cli@0.3.x
          npm run audit:ci --collect.url=$URL_1 --collect.url=$URL_2 || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          URL_1: ${{ steps.waitFor200.outputs.url }}
          URL_2: ${{ steps.waitFor200.outputs.url }}/tabs/tab2

      - name: Netlify build not successful
        if: steps.wait-for-build.outputs.conclusion != 'success'
        run: |
          echo "Netlify build not successful 😢."
